/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;

import javafx.application.Application;
import javafx.scene.input.Clipboard;
import javafx.stage.Stage;


public class App extends Application {
    Window window;
    static File file;

    static StartScene startScene;
    static MainScene mainScene;

    static TickyBoxing tickyboxing;

    static Clipboard clipBoard;

    @Override
    public void start(Stage stage) throws Exception {
        clipBoard = Clipboard.getSystemClipboard();

        window = new Window(stage);

        startScene = new StartScene(stage);
        mainScene = new MainScene(stage);

        window.start();
    }
    public static void main(String[] args) {
        tickyboxing = new TickyBoxing();


        launch(args);
    }
}
