/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;

import javafx.application.Application;
import javafx.geometry.Rectangle2D;
import javafx.scene.image.Image;
import javafx.scene.input.Clipboard;
import javafx.stage.Screen;
import javafx.stage.Stage;


public class App extends Application {
    static Window window;

    static Clipboard clipBoard;
    static Rectangle2D bounds;

    static Stage primaryStage;

    @Override
    public void start(Stage stage) throws Exception {
        primaryStage = stage;
        setup(primaryStage);

        window.start();
    }
    public static void main(String[] args) {
        launch(args);
    }

    private static void setup(Stage stage) {
        clipBoard = Clipboard.getSystemClipboard();
        Screen screen = Screen.getPrimary();

        bounds = screen.getVisualBounds();
        /*
        System.out.println(System.getProperty("user.dir"));
        File file = new File("/src/main/resources/icon.png");
        System.out.println(file.toString());
        */

        Image icon = new Image(App.class.getResourceAsStream("/icon.png"));
        stage.getIcons().add(icon);

        window = new Window(stage);
    }

    public static void reset() {
        setup(primaryStage);
        window.start();
    }


}
